// Fill out your copyright notice in the Description page of Project Settings.


#include "BigInt/BigIntLib.h"


const  FText UBigIntLib::UnitSymbol[UnitSymbolMax] = {
	FText::FromString(TEXT("")),
	FText::FromString(TEXT("만")),
	FText::FromString(TEXT("억")),
	FText::FromString(TEXT("조")),
	FText::FromString(TEXT("경")),
	FText::FromString(TEXT("해")),
	FText::FromString(TEXT("자")),
	FText::FromString(TEXT("양")),
	FText::FromString(TEXT("가")),
	FText::FromString(TEXT("구")),
	FText::FromString(TEXT("간")),
	FText::FromString(TEXT("정")),
	FText::FromString(TEXT("재")),
	FText::FromString(TEXT("극")),
	FText::FromString(TEXT("항")),
	FText::FromString(TEXT("아")),
	FText::FromString(TEXT("나")),
	FText::FromString(TEXT("불")),
	FText::FromString(TEXT("무")),
	FText::FromString(TEXT("겁")),  
	FText::FromString(TEXT("구골")), 
	FText::FromString(TEXT("아산")), 
	FText::FromString(TEXT("센틸")), 
	FText::FromString(TEXT("스큐")),
	FText::FromString(TEXT("구골플")),
	FText::FromString(TEXT("그레")) ,
	FText::FromString(TEXT("파만")),
   FText::FromString(TEXT("파억")),
   FText::FromString(TEXT("파조")),
   FText::FromString(TEXT("파경")),
   FText::FromString(TEXT("파해")),
   FText::FromString(TEXT("파자")),
   FText::FromString(TEXT("파양")),
   FText::FromString(TEXT("파가")),
   FText::FromString(TEXT("파구")),
   FText::FromString(TEXT("파간")),
   FText::FromString(TEXT("파정")),
   FText::FromString(TEXT("파재")),
   FText::FromString(TEXT("파극")),
   FText::FromString(TEXT("파항")),
   FText::FromString(TEXT("파아")),
   FText::FromString(TEXT("파나")),
   FText::FromString(TEXT("파불")),
   FText::FromString(TEXT("파무")),
   FText::FromString(TEXT("파겁")),  
   FText::FromString(TEXT("파구골")), 
   FText::FromString(TEXT("파아산")), 
   FText::FromString(TEXT("파센틸")), 
   FText::FromString(TEXT("파스큐")),
   FText::FromString(TEXT("파구골플")),
   FText::FromString(TEXT("파그레")) 
};